/**
 * 功能映射配置文件
 *
 * 基于 REQ-031 功能表（docs/工程项目管理系统功能表.md）定义所有功能点
 * 与后端模块、前端文件的映射关系。
 *
 * 分类规则：
 * - "二、业务管理" -> PC 端必须 (pcRequired: true)
 * - "三、手机管理功能" -> 移动端必须 (mobileRequired: true)
 * - "四、平台管理功能" -> 仅 PC 端 (pcRequired: true, mobileRequired: false)
 * - 现场管理（施工日志、进度反馈等）-> 双端 (pcRequired: true, mobileRequired: true)
 * - 财务管理（开票、付款、报销等）-> 双端 (pcRequired: true, mobileRequired: true)
 * - 材料库存（入库、出库、退货）-> 双端 (pcRequired: true, mobileRequired: true)
 *
 * Validates: Requirements 5.1, 9.4
 */

import type { FeatureMapping } from '../types';

export const featureMappings: FeatureMapping[] = [
  // ===================== 二、业务管理 =====================

  // --- 2.1 预算管理 ---
  {
    featureId: 'BIZ-2.1-01',
    featureName: '目标成本编制',
    category: '预算管理',
    backendModule: 'budget',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/budget'],
  },
  {
    featureId: 'BIZ-2.1-02',
    featureName: '目标成本变更',
    category: '预算管理',
    backendModule: 'budget',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/budget/change'],
  },

  // --- 2.2 采购管理 ---
  {
    featureId: 'BIZ-2.2-01',
    featureName: '新建材料合同',
    category: '采购管理',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/contract'],
  },
  {
    featureId: 'BIZ-2.2-02',
    featureName: '材料合同结算',
    category: '采购管理',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/settlement'],
  },

  // --- 2.3 三方比价 ---
  {
    featureId: 'BIZ-2.3-01',
    featureName: '询价公告管理',
    category: '三方比价',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/inquiry'],
  },
  {
    featureId: 'BIZ-2.3-02',
    featureName: '供应商报价管理',
    category: '三方比价',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/quotation'],
  },
  {
    featureId: 'BIZ-2.3-03',
    featureName: '报价汇总排名',
    category: '三方比价',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/quotation'],
  },
  {
    featureId: 'BIZ-2.3-04',
    featureName: '中标结果管理',
    category: '三方比价',
    backendModule: 'purchase',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/purchase/bid'],
  },

  // --- 2.4 劳务管理 ---
  {
    featureId: 'BIZ-2.4-01',
    featureName: '劳务分包合同',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/contract'],
  },
  {
    featureId: 'BIZ-2.4-02',
    featureName: '劳务产值上报',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/output-report'],
  },
  {
    featureId: 'BIZ-2.4-03',
    featureName: '劳务合同结算',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/settlement'],
  },
  {
    featureId: 'BIZ-2.4-04',
    featureName: '劳务分包合同奖惩',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/reward-punish'],
  },
  {
    featureId: 'BIZ-2.4-05',
    featureName: '班组管理',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/team'],
  },
  {
    featureId: 'BIZ-2.4-06',
    featureName: '劳务花名册',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/roster'],
  },
  {
    featureId: 'BIZ-2.4-07',
    featureName: '劳务用工单',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/work-order'],
  },
  {
    featureId: 'BIZ-2.4-08',
    featureName: '劳务结算单',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/settlement'],
  },
  {
    featureId: 'BIZ-2.4-09',
    featureName: '劳务薪资统计',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/salary'],
  },
  {
    featureId: 'BIZ-2.4-10',
    featureName: '劳务点工单',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/work-order'],
  },
  {
    featureId: 'BIZ-2.4-11',
    featureName: '点工结算单',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/settlement'],
  },
  {
    featureId: 'BIZ-2.4-12',
    featureName: '点工薪资统计',
    category: '劳务管理',
    backendModule: 'labor',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/labor/salary'],
  },

  // --- 2.5 材料库存 ---
  {
    featureId: 'BIZ-2.5-01',
    featureName: '材料到货入库',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/material/inbound'],
  },
  {
    featureId: 'BIZ-2.5-02',
    featureName: '材料领料出库',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/material/outbound'],
  },
  {
    featureId: 'BIZ-2.5-03',
    featureName: '材料退货出库',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/material/refund'],
  },
  {
    featureId: 'BIZ-2.5-04',
    featureName: '材料调拨',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/material/transfer'],
  },
  {
    featureId: 'BIZ-2.5-05',
    featureName: '材料库存盘点',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/material/inventory'],
  },
  {
    featureId: 'BIZ-2.5-06',
    featureName: '项目材料库存',
    category: '材料库存',
    backendModule: 'material',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/material/inventory'],
  },

  // --- 2.6 机械管理 ---
  {
    featureId: 'BIZ-2.6-01',
    featureName: '机械合同',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/contract'],
  },
  {
    featureId: 'BIZ-2.6-02',
    featureName: '机械使用过程记录',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/usage-record'],
  },
  {
    featureId: 'BIZ-2.6-03',
    featureName: '机械合同结算',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/settlement'],
  },
  {
    featureId: 'BIZ-2.6-04',
    featureName: '机械台账',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/ledger'],
  },
  {
    featureId: 'BIZ-2.6-05',
    featureName: '进场登记',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/entry'],
  },
  {
    featureId: 'BIZ-2.6-06',
    featureName: '出场登记',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/entry'],
  },
  {
    featureId: 'BIZ-2.6-07',
    featureName: '台班/工作量登记',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/work-log'],
  },
  {
    featureId: 'BIZ-2.6-08',
    featureName: '工作量结算',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/settlement'],
  },
  {
    featureId: 'BIZ-2.6-09',
    featureName: '加油登记',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/oil-record'],
  },
  {
    featureId: 'BIZ-2.6-10',
    featureName: '故障报修',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/repair'],
  },
  {
    featureId: 'BIZ-2.6-11',
    featureName: '维修派工',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/repair'],
  },
  {
    featureId: 'BIZ-2.6-12',
    featureName: '维修过程',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/repair'],
  },
  {
    featureId: 'BIZ-2.6-13',
    featureName: '维保记录',
    category: '机械管理',
    backendModule: 'machine',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/machine/repair'],
  },

  // --- 2.7 分包管理 ---
  {
    featureId: 'BIZ-2.7-01',
    featureName: '专业分包合同',
    category: '分包管理',
    backendModule: 'subcontract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/subcontract/contract'],
  },
  {
    featureId: 'BIZ-2.7-02',
    featureName: '分包产值上报',
    category: '分包管理',
    backendModule: 'subcontract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/subcontract/output'],
  },
  {
    featureId: 'BIZ-2.7-03',
    featureName: '专业分包结算',
    category: '分包管理',
    backendModule: 'subcontract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/subcontract/settlement'],
  },
  {
    featureId: 'BIZ-2.7-04',
    featureName: '专业分包合同奖惩',
    category: '分包管理',
    backendModule: 'subcontract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/subcontract/reward-punish'],
  },

  // --- 2.8 现场管理（双端功能）---
  {
    featureId: 'BIZ-2.8-01',
    featureName: '进度计划',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/site/schedule'],
  },
  {
    featureId: 'BIZ-2.8-02',
    featureName: '进度反馈',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/site/schedule'],
  },
  {
    featureId: 'BIZ-2.8-03',
    featureName: '施工日志',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/site/construction-log'],
  },
  {
    featureId: 'BIZ-2.8-04',
    featureName: '质量检查',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/site/inspection'],
  },
  {
    featureId: 'BIZ-2.8-05',
    featureName: '质量整改',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/site/rectification'],
  },
  {
    featureId: 'BIZ-2.8-06',
    featureName: '安全检查',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/site/inspection'],
  },
  {
    featureId: 'BIZ-2.8-07',
    featureName: '安全整改',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/site/rectification'],
  },
  {
    featureId: 'BIZ-2.8-08',
    featureName: '竣工验收',
    category: '现场管理',
    backendModule: 'site',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/site/completion'],
  },

  // --- 2.9 财务管理（双端功能）---
  {
    featureId: 'BIZ-2.9-01',
    featureName: '开票申请',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/invoice-apply'],
  },
  {
    featureId: 'BIZ-2.9-02',
    featureName: '回款登记',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/payment-received'],
  },
  {
    featureId: 'BIZ-2.9-03',
    featureName: '收票登记',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/invoice-received'],
  },
  {
    featureId: 'BIZ-2.9-04',
    featureName: '付款申请',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/payment-apply'],
  },
  {
    featureId: 'BIZ-2.9-05',
    featureName: '其他费用付款',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/other-payment'],
  },
  {
    featureId: 'BIZ-2.9-06',
    featureName: '项目报销',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/project-reimbursement'],
  },
  {
    featureId: 'BIZ-2.9-07',
    featureName: '备用金申请',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/reserve-fund'],
  },
  {
    featureId: 'BIZ-2.9-08',
    featureName: '备用金归还',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/reserve-fund'],
  },
  {
    featureId: 'BIZ-2.9-09',
    featureName: '个人报销',
    category: '财务管理',
    backendModule: 'finance',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/finance/personal-reimbursement'],
  },

  // --- 2.10 行政人事管理 ---
  {
    featureId: 'BIZ-2.10-01',
    featureName: '入职申请',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/entry-apply'],
  },
  {
    featureId: 'BIZ-2.10-02',
    featureName: '转正申请',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/regular-apply'],
  },
  {
    featureId: 'BIZ-2.10-03',
    featureName: '人员调转',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/transfer-apply'],
  },
  {
    featureId: 'BIZ-2.10-04',
    featureName: '离职申请',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/resign-apply'],
  },
  {
    featureId: 'BIZ-2.10-05',
    featureName: '用章申请',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/seal-apply'],
  },
  {
    featureId: 'BIZ-2.10-06',
    featureName: '新增办公用品',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/office-supply'],
  },
  {
    featureId: 'BIZ-2.10-07',
    featureName: '办公用品采购入库',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/office-supply'],
  },
  {
    featureId: 'BIZ-2.10-08',
    featureName: '办公用品领用出库',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/office-supply'],
  },
  {
    featureId: 'BIZ-2.10-09',
    featureName: '车辆登记',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/vehicle'],
  },
  {
    featureId: 'BIZ-2.10-10',
    featureName: '用车申请',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/vehicle'],
  },
  {
    featureId: 'BIZ-2.10-11',
    featureName: '车辆维保&保险',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/hr/vehicle'],
  },
  {
    featureId: 'BIZ-2.10-12',
    featureName: '自持公司档案',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/company'],
  },
  {
    featureId: 'BIZ-2.10-13',
    featureName: '甲方单位档案',
    category: '行政人事',
    backendModule: 'hr',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/owner'],
  },

  // --- 2.11 档案 ---
  {
    featureId: 'BIZ-2.11-01',
    featureName: '项目档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/archive/project'],
  },
  {
    featureId: 'BIZ-2.11-02',
    featureName: '投标档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/tender'],
  },
  {
    featureId: 'BIZ-2.11-03',
    featureName: '目标成本档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/budget'],
  },
  {
    featureId: 'BIZ-2.11-04',
    featureName: '施工合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/contract'],
  },
  {
    featureId: 'BIZ-2.11-05',
    featureName: '供应商档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/supplier'],
  },
  {
    featureId: 'BIZ-2.11-06',
    featureName: '材料合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/material-contract'],
  },
  {
    featureId: 'BIZ-2.11-07',
    featureName: '分包合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/subcontract'],
  },
  {
    featureId: 'BIZ-2.11-08',
    featureName: '其它收入合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/other-income-contract'],
  },
  {
    featureId: 'BIZ-2.11-09',
    featureName: '其它支出合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/other-expense-contract'],
  },
  {
    featureId: 'BIZ-2.11-10',
    featureName: '机械合同档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/machine-contract'],
  },
  {
    featureId: 'BIZ-2.11-11',
    featureName: '人员信息档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/personnel'],
  },
  {
    featureId: 'BIZ-2.11-12',
    featureName: '办公用品档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/office-supply'],
  },
  {
    featureId: 'BIZ-2.11-13',
    featureName: '车辆档案',
    category: '档案管理',
    backendModule: 'archive',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/archive/vehicle'],
  },

  // --- 2.12 基础信息 ---
  {
    featureId: 'BIZ-2.12-01',
    featureName: '材料字典',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/material'],
  },
  {
    featureId: 'BIZ-2.12-02',
    featureName: '自持公司',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/company'],
  },
  {
    featureId: 'BIZ-2.12-03',
    featureName: '供应商管理',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/supplier'],
  },
  {
    featureId: 'BIZ-2.12-04',
    featureName: '甲方单位',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/owner'],
  },
  {
    featureId: 'BIZ-2.12-05',
    featureName: '质量检查方案',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/inspection-scheme'],
  },
  {
    featureId: 'BIZ-2.12-06',
    featureName: '安全检查方案',
    category: '基础信息',
    backendModule: 'basedata',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/basedata/inspection-scheme'],
  },

  // --- 2.13 基础配置 ---
  {
    featureId: 'BIZ-2.13-01',
    featureName: '质保金预警及逾期',
    category: '基础配置',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/finance/retention'],
  },
  {
    featureId: 'BIZ-2.13-02',
    featureName: '预算控制配置',
    category: '基础配置',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/budget-control-configs'],
  },
  {
    featureId: 'BIZ-2.13-03',
    featureName: '二级科目管理',
    category: '基础配置',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/budget/subcategory'],
  },

  // --- 2.14 看板（双端功能）---
  {
    featureId: 'BIZ-2.14-01',
    featureName: '公司经营状况分析',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/company-overview'],
  },
  {
    featureId: 'BIZ-2.14-02',
    featureName: '项目预算执行情况',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/budget-execution'],
  },
  {
    featureId: 'BIZ-2.14-03',
    featureName: '项目应收账款监控',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/receivable-monitor'],
  },
  {
    featureId: 'BIZ-2.14-04',
    featureName: '供应商账款监控',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/supplier-payable'],
  },
  {
    featureId: 'BIZ-2.14-05',
    featureName: '数据看板_投标分析',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/tender-analysis'],
  },
  {
    featureId: 'BIZ-2.14-06',
    featureName: '数据看板_库存分析',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/inventory-analysis'],
  },
  {
    featureId: 'BIZ-2.14-07',
    featureName: '工程进度甘特图',
    category: '看板',
    backendModule: 'dashboard',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/dashboard/schedule-gantt'],
  },

  // ===================== 一、用户管理功能 =====================

  // --- 1.1 用户登录 ---
  {
    featureId: 'USR-1.1-01',
    featureName: '用户登录',
    category: '用户管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/auth', '/v1/captcha'],
  },

  // --- 1.2 首页 ---
  {
    featureId: 'USR-1.2-01',
    featureName: '待办/已办',
    category: '首页',
    backendModule: 'workflow',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/workflow/approval'],
  },
  {
    featureId: 'USR-1.2-02',
    featureName: '快捷入口',
    category: '首页',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/shortcut'],
  },
  {
    featureId: 'USR-1.2-03',
    featureName: '公告',
    category: '首页',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/announcement'],
  },
  {
    featureId: 'USR-1.2-04',
    featureName: '通知',
    category: '首页',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/notice'],
  },
  {
    featureId: 'USR-1.2-05',
    featureName: '消息中心',
    category: '首页',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/msg'],
  },

  // --- 1.3 项目报备 ---
  {
    featureId: 'USR-1.3-01',
    featureName: '项目报备',
    category: '项目管理',
    backendModule: 'project',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/project'],
  },

  // --- 1.4 投标管理 ---
  {
    featureId: 'USR-1.4-01',
    featureName: '投标报名',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/register'],
  },
  {
    featureId: 'USR-1.4-02',
    featureName: '投标任务分配',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/task'],
  },
  {
    featureId: 'USR-1.4-03',
    featureName: '投标费用缴纳',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/fee'],
  },
  {
    featureId: 'USR-1.4-04',
    featureName: '保证金支付申请',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/deposit'],
  },
  {
    featureId: 'USR-1.4-05',
    featureName: '开标记录',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/open-bid'],
  },
  {
    featureId: 'USR-1.4-06',
    featureName: '保证金退回登记',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/deposit'],
  },
  {
    featureId: 'USR-1.4-07',
    featureName: '人员证件',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/certificate'],
  },
  {
    featureId: 'USR-1.4-08',
    featureName: '公司证件',
    category: '投标管理',
    backendModule: 'tender',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/tender/certificate'],
  },

  // --- 1.5 项目管理 ---
  {
    featureId: 'USR-1.5-01',
    featureName: '施工合同登记',
    category: '项目管理',
    backendModule: 'contract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract'],
  },
  {
    featureId: 'USR-1.5-02',
    featureName: '工程量清单上传',
    category: '项目管理',
    backendModule: 'project',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract/quantity'],
  },
  {
    featureId: 'USR-1.5-03',
    featureName: '产值上报',
    category: '项目管理',
    backendModule: 'project',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract/output'],
  },
  {
    featureId: 'USR-1.5-04',
    featureName: '项目最终结算',
    category: '项目管理',
    backendModule: 'project',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract/settlement'],
  },
  {
    featureId: 'USR-1.5-05',
    featureName: '其它收入合同',
    category: '项目管理',
    backendModule: 'contract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract/other'],
  },
  {
    featureId: 'USR-1.5-06',
    featureName: '其它支出合同',
    category: '项目管理',
    backendModule: 'contract',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/contract/other'],
  },

  // ===================== 三、手机管理功能（移动端必须）=====================

  // 注意：移动端的看板、财务、现场管理、材料等功能已在上方标记为双端
  // 以下仅列出移动端独有的功能条目

  {
    featureId: 'MOB-3.2-01',
    featureName: '常用功能（移动端）',
    category: '移动端首页',
    backendModule: 'system',
    pcRequired: false,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/shortcut'],
  },
  {
    featureId: 'MOB-3.2-02',
    featureName: '信息中心（移动端）',
    category: '移动端首页',
    backendModule: 'system',
    pcRequired: false,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/message/msg', '/v1/message/notice'],
  },
  {
    featureId: 'MOB-3.2-03',
    featureName: '我的审批（移动端）',
    category: '移动端首页',
    backendModule: 'workflow',
    pcRequired: false,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/workflow/approval'],
  },
  {
    featureId: 'MOB-3.3-01',
    featureName: '项目看板（移动端）',
    category: '移动端工作台',
    backendModule: 'dashboard',
    pcRequired: false,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/dashboard/project'],
  },
  {
    featureId: 'MOB-3.4-01',
    featureName: '切换账户',
    category: '移动端我的',
    backendModule: 'system',
    pcRequired: false,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/auth'],
  },
  {
    featureId: 'MOB-3.4-02',
    featureName: '密码修改',
    category: '移动端我的',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: true,
    expectedApiPatterns: ['/v1/auth/password-reset'],
  },

  // ===================== 四、平台管理功能（仅PC端）=====================

  // --- 4.2 系统管理 ---
  {
    featureId: 'PLT-4.2-01',
    featureName: '机构管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/org'],
  },
  {
    featureId: 'PLT-4.2-02',
    featureName: '岗位管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/post'],
  },
  {
    featureId: 'PLT-4.2-03',
    featureName: '人员管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/user'],
  },
  {
    featureId: 'PLT-4.2-04',
    featureName: '角色管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/role'],
  },
  {
    featureId: 'PLT-4.2-05',
    featureName: '菜单管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/menu'],
  },
  {
    featureId: 'PLT-4.2-06',
    featureName: '数据权限',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/role'],
  },
  {
    featureId: 'PLT-4.2-07',
    featureName: '数据字典',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/dict'],
  },
  {
    featureId: 'PLT-4.2-08',
    featureName: '系统设置',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/config'],
  },
  {
    featureId: 'PLT-4.2-09',
    featureName: '存储管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/file/storage'],
  },
  {
    featureId: 'PLT-4.2-10',
    featureName: '日志管理',
    category: '系统管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/system/log', '/v1/system/audit'],
  },

  // --- 4.3 用户管理 ---
  {
    featureId: 'PLT-4.3-01',
    featureName: '用户类型',
    category: '平台用户管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/platform/tenant-type'],
  },
  {
    featureId: 'PLT-4.3-02',
    featureName: '用户信息',
    category: '平台用户管理',
    backendModule: 'system',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/platform/tenant'],
  },

  // --- 4.4 流程管理 ---
  {
    featureId: 'PLT-4.4-01',
    featureName: '业务类型',
    category: '流程管理',
    backendModule: 'workflow',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/workflow/business-type'],
  },
  {
    featureId: 'PLT-4.4-02',
    featureName: '流程设计',
    category: '流程管理',
    backendModule: 'workflow',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/workflow/process'],
  },
  {
    featureId: 'PLT-4.4-03',
    featureName: '流程定义',
    category: '流程管理',
    backendModule: 'workflow',
    pcRequired: true,
    mobileRequired: false,
    expectedApiPatterns: ['/v1/workflow/process'],
  },
];
