#!/usr/bin/env bash
# 任务 3.1：只读校验目标库/表字符集与排序规则（utf8mb4 / utf8mb4_general_ci）
# 口令仅以变量引用，不回显明文
PW=zwinsight123
DB=zw_insight
Q() { docker exec -i zwi-mysql sh -c "mysql -uroot -p$PW -N -e \"$1\"" 2>/dev/null; }

echo "===1_CHARACTER_SET_VARIABLES==="
Q "SHOW VARIABLES LIKE 'character_set%';"

echo "===2_COLLATION_VARIABLES==="
Q "SHOW VARIABLES LIKE 'collation%';"

echo "===3_SCHEMA_DEFAULT==="
Q "SELECT SCHEMA_NAME, DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM information_schema.SCHEMATA WHERE SCHEMA_NAME='$DB';"

echo "===4_TABLES_COLLATION==="
Q "SELECT TABLE_NAME, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA='$DB' ORDER BY TABLE_NAME;"

echo "===5_NON_UTF8MB4_TABLES==="
Q "SELECT TABLE_NAME, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA='$DB' AND (TABLE_COLLATION IS NOT NULL AND TABLE_COLLATION NOT LIKE 'utf8mb4%') ORDER BY TABLE_NAME;"

echo "===6_NON_GENERAL_CI_TABLES==="
Q "SELECT TABLE_NAME, TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA='$DB' AND TABLE_COLLATION IS NOT NULL AND TABLE_COLLATION <> 'utf8mb4_general_ci' ORDER BY TABLE_NAME;"

echo "===7_NON_UTF8MB4_COLUMNS==="
Q "SELECT TABLE_NAME, COLUMN_NAME, CHARACTER_SET_NAME, COLLATION_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='$DB' AND CHARACTER_SET_NAME IS NOT NULL AND CHARACTER_SET_NAME <> 'utf8mb4' ORDER BY TABLE_NAME, COLUMN_NAME;"

echo "===8_TABLE_COUNT==="
Q "SELECT COUNT(*) AS total_tables FROM information_schema.TABLES WHERE TABLE_SCHEMA='$DB';"

echo "===DONE==="
